//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.Resource.WebHost.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index_cshtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_cshtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vnsf.Resource.WebHost.Views.Home.Index.cshtml", typeof(Index_cshtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply now.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you ready for challenge?.
        /// </summary>
        public static string Areyouready {
            get {
                return ResourceManager.GetString("Areyouready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Development Challenges.
        /// </summary>
        public static string C1 {
            get {
                return ResourceManager.GetString("C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key development problems which need to be addressed as national priorities to make contribution to the achievement of targets set forth in the Viet Nam socio-economic development strategy period 2011-2020..
        /// </summary>
        public static string C1_detail {
            get {
                return ResourceManager.GetString("C1_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Adaptation and Upgrading.
        /// </summary>
        public static string C2 {
            get {
                return ResourceManager.GetString("C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To stimulate the adaptation and upgrading of existing research and/or prototype technologies for development of (pilot) products up to the level ready for scaling-up and/or commercialization..
        /// </summary>
        public static string C2_detail {
            get {
                return ResourceManager.GetString("C2_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grassroots.
        /// </summary>
        public static string C3 {
            get {
                return ResourceManager.GetString("C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To stimulate inclusive innovations from an informal sector (the grass root innovator). To support the scaling up, creation and commercialization of high volume, low cost products that can reach a significant size of BoP people..
        /// </summary>
        public static string C3_detail {
            get {
                return ResourceManager.GetString("C3_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling up and Commercialization.
        /// </summary>
        public static string C4 {
            get {
                return ResourceManager.GetString("C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To bring the technologies previously developed or transferred into a larger sustainable production scale..
        /// </summary>
        public static string C4_detail {
            get {
                return ResourceManager.GetString("C4_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each project.
        /// </summary>
        public static string Each {
            get {
                return ResourceManager.GetString("Each", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICT Application as a Tool for Delivery of Services to the BoP.
        /// </summary>
        public static string F1 {
            get {
                return ResourceManager.GetString("F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific NDCs to be addressed: Enhance the availability, relevance and access to information and contents targeted at the BoP.
        ///Develop/design affordable, durable and user friendly ICT devices / applications for the benefits of BoP..
        /// </summary>
        public static string F1_detail {
            get {
                return ResourceManager.GetString("F1_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agriculture/Aquaculture Technologies.
        /// </summary>
        public static string F2 {
            get {
                return ResourceManager.GetString("F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific NDCs to be addressed: Develop technology solutions to reduce post-harvest losses in agriculture/aquaculture products.
        ///Improve quality and safety of agriculture/aquaculture products.
        ///Develop clean energy/ energy efficient solutions for use by villagers and farmers to improve life quality and productivity..
        /// </summary>
        public static string F2_detail {
            get {
                return ResourceManager.GetString("F2_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional herbal medicine.
        /// </summary>
        public static string F3 {
            get {
                return ResourceManager.GetString("F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific NDCs to be addressed: Quality enhancement in the entire value chain of herbal medicine development, including cultivation, production, manufacturing, distribution and marketing of herbal medicines
        ///Technology upgrading in the entire value chain of herbal medicine development, including cultivation, production, manufacturing, distribution and marketing with Good Manufacturing Practice (GMP) standards.
        /// </summary>
        public static string F3_detail {
            get {
                return ResourceManager.GetString("F3_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEARN MORE.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority fields.
        /// </summary>
        public static string PriorityField {
            get {
                return ResourceManager.GetString("PriorityField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance sub-projects in applied research and technology development areas, thematically assigned to innovative technologies of high utilization potential and of particular importance for Viet Nam under the following three themes identified by the NDC Council:.
        /// </summary>
        public static string PriorityField_detail {
            get {
                return ResourceManager.GetString("PriorityField_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If so, why don’t you get in touch with us so we can talk about your projects..
        /// </summary>
        public static string ReadyAnswer {
            get {
                return ResourceManager.GetString("ReadyAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover. Develop. Deliver..
        /// </summary>
        public static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnam Inclusive Innovation Project.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total funding.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
    }
}
