//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.OMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class omsEntities : DbContext
    {
        public omsEntities()
            : base("name=omsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<basi_main_temp> basi_main_temp { get; set; }
        public DbSet<basic_main> basic_main { get; set; }
        public DbSet<basic_main_pub> basic_main_pub { get; set; }
        public DbSet<exp_basics> exp_basics { get; set; }
        public DbSet<proposal_en> proposal_en { get; set; }
        public DbSet<tbl_action> tbl_action { get; set; }
        public DbSet<tbl_education> tbl_education { get; set; }
        public DbSet<tbl_eval_basic> tbl_eval_basic { get; set; }
        public DbSet<tbl_eval_ha> tbl_eval_ha { get; set; }
        public DbSet<tbl_eval_report> tbl_eval_report { get; set; }
        public DbSet<tbl_fields> tbl_fields { get; set; }
        public DbSet<tbl_fields_old> tbl_fields_old { get; set; }
        public DbSet<tbl_finare_edu> tbl_finare_edu { get; set; }
        public DbSet<tbl_finare_file> tbl_finare_file { get; set; }
        public DbSet<tbl_finare_list> tbl_finare_list { get; set; }
        public DbSet<tbl_finare_person> tbl_finare_person { get; set; }
        public DbSet<tbl_finare_pub> tbl_finare_pub { get; set; }
        public DbSet<tbl_finare_pubtemp> tbl_finare_pubtemp { get; set; }
        public DbSet<tbl_finare_use> tbl_finare_use { get; set; }
        public DbSet<tbl_finareb> tbl_finareb { get; set; }
        public DbSet<tbl_if> tbl_if { get; set; }
        public DbSet<tbl_invest_list> tbl_invest_list { get; set; }
        public DbSet<tbl_issn_temp> tbl_issn_temp { get; set; }
        public DbSet<tbl_journal> tbl_journal { get; set; }
        public DbSet<tbl_main_profile> tbl_main_profile { get; set; }
        public DbSet<tbl_moderator> tbl_moderator { get; set; }
        public DbSet<tbl_org> tbl_org { get; set; }
        public DbSet<tbl_panel> tbl_panel { get; set; }
        public DbSet<tbl_profile> tbl_profile { get; set; }
        public DbSet<tbl_profile_nomin> tbl_profile_nomin { get; set; }
        public DbSet<tbl_profile_nomin_list> tbl_profile_nomin_list { get; set; }
        public DbSet<tbl_profile_nomin_vote> tbl_profile_nomin_vote { get; set; }
        public DbSet<tbl_profile_tmp> tbl_profile_tmp { get; set; }
        public DbSet<tbl_program_type> tbl_program_type { get; set; }
        public DbSet<tbl_project> tbl_project { get; set; }
        public DbSet<tbl_publication> tbl_publication { get; set; }
        public DbSet<tbl_report> tbl_report { get; set; }
        public DbSet<tbl_result> tbl_result { get; set; }
        public DbSet<tbl_result_edu> tbl_result_edu { get; set; }
        public DbSet<tbl_review> tbl_review { get; set; }
        public DbSet<tbl_s_title> tbl_s_title { get; set; }
        public DbSet<tbl_sci> tbl_sci { get; set; }
        public DbSet<tbl_tmp> tbl_tmp { get; set; }
        public DbSet<tbl_work> tbl_work { get; set; }
    }
}
