//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.OMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_report
    {
        public int R_ID { get; set; }
        public int S_ID { get; set; }
        public int B_ID { get; set; }
        public string R_TYPE { get; set; }
        public string R_DONE { get; set; }
        public string R_PROCESSING { get; set; }
        public string R_QUALITY { get; set; }
        public string R_OTHER { get; set; }
        public Nullable<double> R_EXPENSE_1 { get; set; }
        public Nullable<double> R_EXPENSE_OUT { get; set; }
        public Nullable<double> R_EXPENSE_IN { get; set; }
        public string R_EXPENSE_UPLOAD { get; set; }
        public string R_EXIST { get; set; }
        public string R_NEXT { get; set; }
        public string R_CONCLUSION { get; set; }
        public string R_UPDATE_DATE { get; set; }
        public string R_CREATED_DATE { get; set; }
        public string R_SUBMITTED { get; set; }
        public string R_SUBMITTED_DATE { get; set; }
        public string R_KEY { get; set; }
        public string E_MARK { get; set; }
        public string E_COMMENT { get; set; }
        public string S_STATUS { get; set; }
        public string S_PROPOSAL { get; set; }
        public string S_CMT { get; set; }
        public string F_STATUS { get; set; }
        public string F_PROPOSAL { get; set; }
        public string F_CMT { get; set; }
        public string R_EXTENSION { get; set; }
        public string R_BDATE { get; set; }
    }
}
