//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.OMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tmp
    {
        public int ID { get; set; }
        public string PROJECT_NAME { get; set; }
        public string PROJECT_CODE { get; set; }
        public string S_NAME { get; set; }
        public string S_EMAIL { get; set; }
        public int DATE { get; set; }
    }
}
