//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.OMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_profile_nomin_list
    {
        public int id { get; set; }
        public int S_ID { get; set; }
        public string name { get; set; }
        public string topo { get; set; }
        public string @public { get; set; }
        public string @abstract { get; set; }
    }
}
