//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.OMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_project
    {
        public int P_ID { get; set; }
        public int S_ID { get; set; }
        public sbyte P_LANGUAGE { get; set; }
        public string P_NAME { get; set; }
        public string P_NAME_E { get; set; }
        public string P_ROLE { get; set; }
        public string P_ROLE_E { get; set; }
        public string P_ORGANIZATION { get; set; }
        public string P_ORGANIZATION_E { get; set; }
        public string P_ORGANIZATION_LOCATION { get; set; }
        public string P_ORGANIZATION_WEBSITE { get; set; }
        public string P_FROM { get; set; }
        public string P_TO { get; set; }
        public Nullable<int> P_EXPENSE { get; set; }
        public string P_CURRENCY { get; set; }
        public Nullable<double> P_MONTH_NUM { get; set; }
        public string P_NOTE { get; set; }
        public string P_UPDATE_DATE { get; set; }
        public string P_KEY { get; set; }
    }
}
