//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.OMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fields_old
    {
        public string F_CODE { get; set; }
        public string F_PARENT { get; set; }
        public string F_NAME { get; set; }
        public string F_NAME_E { get; set; }
        public string F_DATE_S { get; set; }
    }
}
