//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.OMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_finare_file
    {
        public int id { get; set; }
        public int idl { get; set; }
        public int extra { get; set; }
        public string basename { get; set; }
        public string filename { get; set; }
        public string ex { get; set; }
    }
}
