// <auto-generated />
namespace Vnsf.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class useraccount_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(useraccount_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201404150853215_useraccount_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
