//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.Anticorruption
{
    using System;
    using System.Collections.Generic;
    
    public partial class proposal_en
    {
        public string B_CODE { get; set; }
        public string B_NAME_E { get; set; }
    }
}
