//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.Anticorruption
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_work
    {
        public int W_ID { get; set; }
        public int S_ID { get; set; }
        public sbyte W_LANGUAGE { get; set; }
        public string W_NAME { get; set; }
        public string W_NAME_E { get; set; }
        public string W_LOCATION { get; set; }
        public string W_FROM { get; set; }
        public string W_TO { get; set; }
        public string W_PHONE { get; set; }
        public string W_TITLE { get; set; }
        public string W_TITLE_E { get; set; }
        public string W_NOTE { get; set; }
        public string W_KEY { get; set; }
        public string W_UPDATE_DATE { get; set; }
    }
}
