//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.Anticorruption
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_profile_tmp
    {
        public int S_ID { get; set; }
        public string S_NAME { get; set; }
        public string S_EMAIL { get; set; }
        public string S_PASSWORD_TMP { get; set; }
        public string S_PASSWORD { get; set; }
        public string S_KEY { get; set; }
        public string S_DATE { get; set; }
    }
}
