//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.Anticorruption
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_program_type
    {
        public int T_ID { get; set; }
        public string T_NAME { get; set; }
        public string T_NAME_E { get; set; }
        public string T_SHORT { get; set; }
        public string T_LONG { get; set; }
        public string T_LONG_E { get; set; }
        public string T_PARTNER { get; set; }
        public string T_WEBSITE { get; set; }
        public string T_M2_LINK { get; set; }
        public string T_M2_LINK_E { get; set; }
        public Nullable<int> T_SUBMITABLE { get; set; }
        public string T_DEADLINE { get; set; }
        public Nullable<int> T_ENG_REQUIRED { get; set; }
        public Nullable<int> T_DATE { get; set; }
        public int T_TYPE { get; set; }
    }
}
