//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.Anticorruption
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_profile_nomin
    {
        public int id { get; set; }
        public int S_ID { get; set; }
        public int numisi { get; set; }
        public int ck_panel { get; set; }
        public int ck_hope { get; set; }
        public int addtime { get; set; }
    }
}
