//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.Anticorruption
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invest_list
    {
        public int id { get; set; }
        public string project_name { get; set; }
        public string project_code { get; set; }
        public string project_main { get; set; }
        public int research { get; set; }
        public int progress { get; set; }
        public int addtime { get; set; }
        public int edittime { get; set; }
        public int userid { get; set; }
        public string note { get; set; }
        public string adjust { get; set; }
        public int actiontime { get; set; }
        public int year { get; set; }
        public int phd_reg { get; set; }
        public int phd_get { get; set; }
        public int grad_reg { get; set; }
        public int grad_get { get; set; }
        public int wor_reg { get; set; }
        public int wor_pubsci { get; set; }
        public int wor_acesci { get; set; }
        public int wor_sensci { get; set; }
        public int wor_pubscie { get; set; }
        public int wor_acescie { get; set; }
        public int wor_senscie { get; set; }
        public int notisi_reg { get; set; }
        public int notisi_pub { get; set; }
        public int notisi_ace { get; set; }
        public int notisi_sen { get; set; }
        public int spec_reg { get; set; }
        public int spec_pub { get; set; }
        public int spec_ace { get; set; }
        public int spec_sen { get; set; }
        public int inter_reg { get; set; }
        public int inter_pub { get; set; }
        public int inter_ace { get; set; }
        public int inter_sen { get; set; }
        public int nati_reg { get; set; }
        public int nati_pub { get; set; }
        public int nati_ace { get; set; }
        public int nati_sen { get; set; }
        public int book_reg { get; set; }
        public int book_pub { get; set; }
        public int book_ace { get; set; }
        public int book_sen { get; set; }
        public int pat_reg { get; set; }
        public int pat_pub { get; set; }
        public int pat_ace { get; set; }
        public int pat_sen { get; set; }
        public int res_reg { get; set; }
        public int res_pub { get; set; }
        public int res_ace { get; set; }
        public int res_sen { get; set; }
        public string descript { get; set; }
    }
}
