//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.OMS.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class basi_main_temp
    {
        public int ID { get; set; }
        public Nullable<int> B_ID { get; set; }
        public string B_NAME_V { get; set; }
        public string B_CODE { get; set; }
        public Nullable<int> T_DATE { get; set; }
        public string B_MAJOR { get; set; }
        public string S_NAME { get; set; }
        public string S_ORG { get; set; }
        public string B_STATUS { get; set; }
        public int B_FUNDED { get; set; }
    }
}
