//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.OMS.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_finare_person
    {
        public int id { get; set; }
        public int idl { get; set; }
        public string name { get; set; }
        public string organ { get; set; }
        public string position { get; set; }
    }
}
