//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.OMS.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_org
    {
        public long id { get; set; }
        public string org_name { get; set; }
        public Nullable<int> org_parent { get; set; }
        public string org_addr { get; set; }
        public string org_city { get; set; }
        public string org_state { get; set; }
        public Nullable<bool> org_area { get; set; }
        public string org_country { get; set; }
        public string org_bank_acc { get; set; }
        public string org_bank_name { get; set; }
        public string org_phone { get; set; }
        public string org_phone1 { get; set; }
        public string org_phone2 { get; set; }
        public string org_fax { get; set; }
        public string org_email { get; set; }
        public string org_type { get; set; }
    }
}
