//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.OMS.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_education
    {
        public int E_ID { get; set; }
        public int S_ID { get; set; }
        public sbyte E_LANGUAGE { get; set; }
        public string E_NAME { get; set; }
        public string E_NAME_E { get; set; }
        public string E_LOCATION { get; set; }
        public string E_MAJOR { get; set; }
        public string E_MAJOR_E { get; set; }
        public string E_DEGREE { get; set; }
        public string E_DEGREE_E { get; set; }
        public string E_CERTIFICATE_UPLOAD { get; set; }
        public string E_FROM { get; set; }
        public string E_TO { get; set; }
        public string E_KEY { get; set; }
        public string E_UPDATE_DATE { get; set; }
    }
}
