//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.OMS.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_profile
    {
        public int S_ID { get; set; }
        public sbyte S_LANGUAGE { get; set; }
        public string S_TYPE { get; set; }
        public string S_EXPERT { get; set; }
        public string S_NAME { get; set; }
        public string S_PASSWORD_TMP { get; set; }
        public string S_PASSWORD { get; set; }
        public string S_GENDER { get; set; }
        public string S_BIRTHDATE { get; set; }
        public string S_SCIENTIFICE_TITLE { get; set; }
        public string S_MAJOR { get; set; }
        public string S_SIGN_UPLOAD { get; set; }
        public string S_FIELD_CODE { get; set; }
        public string S_FIELD { get; set; }
        public string S_SECOND_FIELD_CODE { get; set; }
        public string S_SECOND_FIELD { get; set; }
        public string S_THIRD_FIELD_CODE { get; set; }
        public string S_THIRD_FIELD { get; set; }
        public string S_ADMINISTRATIVE_TITLE { get; set; }
        public string S_ADMINISTRATIVE_TITLE_E { get; set; }
        public string S_GOVER_NAME { get; set; }
        public string S_OFFICE_NAME { get; set; }
        public string S_OFFICE_NAME_E { get; set; }
        public string S_OFFICE_DEPT { get; set; }
        public string S_OFFICE_ADD { get; set; }
        public string S_OFFICE_CITY { get; set; }
        public string S_OFFICE_FAX { get; set; }
        public string S_EMAIL_P { get; set; }
        public string S_EMAIL_S { get; set; }
        public string S_HOME_PHONE { get; set; }
        public string S_OFFICE_PHONE { get; set; }
        public string S_CELL_PHONE { get; set; }
        public string S_HOME_ADD { get; set; }
        public string S_HOME_CITY { get; set; }
        public string S_ACC_NUMBER { get; set; }
        public string S_ACC_BANK { get; set; }
        public string S_RESEARCH_ORIENTATION { get; set; }
        public string S_RESEARCH_ORIENTATION_E { get; set; }
        public string S_PUBLICATION { get; set; }
        public string S_RESEARCH_UPDATE_DATE { get; set; }
        public string S_E_READING { get; set; }
        public string S_E_WRITING { get; set; }
        public string S_E_SPEAKING { get; set; }
        public string S_O_READING { get; set; }
        public string S_O_WRITING { get; set; }
        public string S_O_SPEAKING { get; set; }
        public Nullable<int> S_SCI { get; set; }
        public Nullable<int> S_SCIE { get; set; }
        public string S_COMMENT { get; set; }
        public string S_COMMENT_E { get; set; }
        public string S_REGISTERED_DATE { get; set; }
        public string S_ACTIVATED_DATE { get; set; }
        public string S_LASTLOGIN_DATE { get; set; }
        public string S_UPDATE_DATE { get; set; }
        public string S_KEY { get; set; }
        public string S_LASTCHECK_DATE { get; set; }
        public int S_VOTE { get; set; }
        public Nullable<int> S_UPDATED_TIME { get; set; }
        public Nullable<int> S_ORG_ID { get; set; }
        public string S_NUMBER_ID { get; set; }
    }
}
