//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.OMS.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_profile_nomin_vote
    {
        public int id { get; set; }
        public int S_ID { get; set; }
        public int S_IDV { get; set; }
        public int value { get; set; }
        public string s_type { get; set; }
        public int year { get; set; }
        public int vote { get; set; }
    }
}
