//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.OMS.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_finareb
    {
        public int idl { get; set; }
        public int id { get; set; }
        public string B_CODE { get; set; }
        public Nullable<int> ISI { get; set; }
        public Nullable<int> tcqt { get; set; }
        public Nullable<int> tcqg { get; set; }
        public Nullable<int> htqt { get; set; }
        public Nullable<int> htqg { get; set; }
        public string other { get; set; }
        public Nullable<int> ths { get; set; }
        public Nullable<int> ts { get; set; }
    }
}
