//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vnsf.OMS.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_finare_pubtemp
    {
        public int id { get; set; }
        public int idl { get; set; }
        public int idc { get; set; }
        public string title { get; set; }
        public string num { get; set; }
        public int accept { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public string issn { get; set; }
        public int year { get; set; }
    }
}
