//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class basic_main_pub
    {
        public int id { get; set; }
        public int bid { get; set; }
        public int cate { get; set; }
        public int name { get; set; }
        public int num { get; set; }
        public string note { get; set; }
    }
}
