//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class basic_main
    {
        public int B_ID { get; set; }
        public sbyte B_LANGUAGE { get; set; }
        public string B_NAME_V { get; set; }
        public string B_NAME_E { get; set; }
        public string B_FUNDED { get; set; }
        public string B_VALLID { get; set; }
        public Nullable<int> T_ID { get; set; }
        public int T_DATE { get; set; }
        public string B_CODE { get; set; }
        public string B_PROPOSAL { get; set; }
        public string B_MAJOR { get; set; }
        public string B_FIELD { get; set; }
        public string B_FIELD_CODE { get; set; }
        public string B_GROUP { get; set; }
        public string B_TYPE { get; set; }
        public string B_START_MONTH { get; set; }
        public Nullable<int> B_FINAL_MONTH { get; set; }
        public string B_FROM { get; set; }
        public string B_TO { get; set; }
        public Nullable<int> B_MONTH_NUMBER { get; set; }
        public Nullable<int> B_PEOPLE_NUMBER { get; set; }
        public Nullable<int> B_TOTAL_EXPENSE { get; set; }
        public Nullable<int> B_REQUESTED_EXPENSE { get; set; }
        public Nullable<double> B_PASS_EXPENSE { get; set; }
        public Nullable<double> B_FINAL_EXPENSE { get; set; }
        public string B_SPONSORS { get; set; }
        public Nullable<int> B_ORG_ID { get; set; }
        public string B_MAIN_ORG { get; set; }
        public string B_MAIN_ORG_E { get; set; }
        public string B_MAIN_ORG_ADD { get; set; }
        public string B_MAIN_ORG_CITY { get; set; }
        public string B_MAIN_ORG_REP { get; set; }
        public string B_MAIN_ORG_REP_POS { get; set; }
        public string B_MAIN_ORG_REP_TITLE { get; set; }
        public string B_MAIN_ORG_ACC { get; set; }
        public string B_MAIN_ORG_BANK { get; set; }
        public string B_MAIN_ORG_UPLOAD { get; set; }
        public string B_MAIN_ORG_UPLOAD_E { get; set; }
        public string B_SECOND_ORG { get; set; }
        public string B_SECOND_ORG_E { get; set; }
        public string B_SECOND_ORG_ADD { get; set; }
        public string B_SECOND_ORG_CITY { get; set; }
        public string B_SECOND_ORG_REP { get; set; }
        public string B_SECOND_ORG_REP_POS { get; set; }
        public string B_SECOND_ORG_REP_TITLE { get; set; }
        public string B_SECOND_ORG_EMAIL { get; set; }
        public string B_SECOND_ORG_ACC { get; set; }
        public string B_SECOND_ORG_BANK { get; set; }
        public string B_SECOND_ORG_FACILITY { get; set; }
        public string B_SECOND_ORG_FACILITY_E { get; set; }
        public string B_SECOND_ORG_TEL { get; set; }
        public string B_SECOND_ORG_UPLOAD { get; set; }
        public string B_SECOND_ORG_UPLOAD_E { get; set; }
        public string B_SECOND_PRO_NAME { get; set; }
        public string B_SECOND_PRO_GENDER { get; set; }
        public string B_SECOND_PRO_BIRTHDATE { get; set; }
        public string B_SECOND_PRO_SCIENTIFICE_TITLE { get; set; }
        public string B_SECOND_PRO_NUMBER_ID { get; set; }
        public string B_SECOND_PRO_OFFICE_DEPT { get; set; }
        public string B_SECOND_PRO_ADMINISTRATIVE_TITLE { get; set; }
        public string B_SECOND_PRO_OFFICE_NAME { get; set; }
        public string B_SECOND_PRO_OFFICE_ADD { get; set; }
        public string B_SECOND_PRO_OFFICE_CITY { get; set; }
        public string B_SECOND_PRO_OFFICE_PHONE { get; set; }
        public string B_SECOND_PRO_CELL_PHONE { get; set; }
        public string B_SECOND_PRO_EMAIL { get; set; }
        public string B_SECOND_PRO_OFFICE_FAX { get; set; }
        public string B_PROPOSAL_UPLOAD { get; set; }
        public string B_PROPOSAL_UPLOAD_E { get; set; }
        public string B_STATUS { get; set; }
        public string B_S_ID { get; set; }
        public string B_UPDATE_DATE { get; set; }
        public Nullable<int> B_UPDATE_PERSON { get; set; }
        public Nullable<int> B_CREATED_ID { get; set; }
        public string B_CREATED_DATE { get; set; }
        public sbyte B_SUBMITTED { get; set; }
        public sbyte B_HARD_SUBMITTED { get; set; }
        public string B_SUBMITTED_DATE { get; set; }
        public Nullable<int> B_SUBMITTED_ID { get; set; }
        public string BS_STATUS { get; set; }
        public string BS_PROPOSAL { get; set; }
        public string BS_CMT { get; set; }
        public string BF_STATUS { get; set; }
        public string BF_PROPOSAL { get; set; }
        public string BF_CMT { get; set; }
        public Nullable<int> S_ID_1 { get; set; }
        public Nullable<int> S_ID_2 { get; set; }
        public Nullable<int> S_ID_3 { get; set; }
        public Nullable<int> S_ID_4 { get; set; }
        public string B_TK_UPDATE { get; set; }
        public string B_KEY { get; set; }
        public string B_FACILITY { get; set; }
        public string B_FACILITY_E { get; set; }
        public string EXP1_NAME { get; set; }
        public string EXP1_FIELD { get; set; }
        public string EXP1_ORG { get; set; }
        public string EXP1_CONTACT { get; set; }
        public string EXP2_NAME { get; set; }
        public string EXP2_FIELD { get; set; }
        public string EXP2_ORG { get; set; }
        public string EXP2_CONTACT { get; set; }
        public string EXP3_NAME { get; set; }
        public string EXP3_FIELD { get; set; }
        public string EXP3_ORG { get; set; }
        public string EXP3_CONTACT { get; set; }
        public string EXP1_FIELD_E { get; set; }
        public string EXP2_FIELD_E { get; set; }
        public string EXP3_FIELD_E { get; set; }
        public string EXP4_FIELD_E { get; set; }
        public Nullable<int> B_SUBMITTED_DATE_N { get; set; }
        public int B_DATE_HARD_COPY { get; set; }
        public string B_VALLID_REASONS { get; set; }
        public string B_VALLID_NOTE { get; set; }
        public double B_EXPENSE_LABOR { get; set; }
        public int B_NUM_PUBISI { get; set; }
        public string B_NUM_PUBISI_NOTE { get; set; }
        public int B_NUM_PUBINTER { get; set; }
        public string B_NUM_PUBINTER_NOTE { get; set; }
        public int B_NUM_BOOK { get; set; }
        public string B_NUM_BOOK_NOTE { get; set; }
        public int B_NUM_PATENT { get; set; }
        public Nullable<int> B_NUM_CEMINA { get; set; }
        public string B_NUM_CEMINA_NOTE { get; set; }
        public Nullable<int> B_NUM_NATION { get; set; }
        public string B_NUM_NATION_NOTE { get; set; }
        public string B_OTHER_PRODUCTS { get; set; }
        public string B_OTHER_PRODUCTS_NOTE { get; set; }
        public int B_MASTER { get; set; }
        public string B_MASTER_NOTE { get; set; }
        public int B_PHD { get; set; }
        public string B_PHD_NOTE { get; set; }
        public double B_MATERIAL_COST { get; set; }
        public double B_TOOLS_COST { get; set; }
        public double B_TRAVEL_COST { get; set; }
        public double B_SERVICES_COST { get; set; }
        public double B_DIRECT_COST { get; set; }
        public double B_INDIRECT_COST { get; set; }
        public string B_REVIEW_NOTE { get; set; }
        public string B_ABSTRACT_V { get; set; }
        public string B_ABSTRACT_E { get; set; }
    }
}
