//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exp_basics
    {
        public int S_ID { get; set; }
        public int B_ID { get; set; }
        public Nullable<int> E_MARK_1 { get; set; }
        public string E_COMMENT_1 { get; set; }
        public Nullable<int> E_MARK_2 { get; set; }
        public string E_COMMENT_2 { get; set; }
        public Nullable<int> E_MARK_3 { get; set; }
        public string E_COMMENT_3 { get; set; }
        public Nullable<int> E_MARK_4 { get; set; }
        public string E_COMMENT_4 { get; set; }
        public Nullable<int> E_MARK_5 { get; set; }
        public string E_COMMENT_5 { get; set; }
        public Nullable<int> E_MARK_6 { get; set; }
        public string E_COMMENT_6 { get; set; }
        public Nullable<int> E_MARK_SUM { get; set; }
        public string E_RANK { get; set; }
        public string E_COMMENT { get; set; }
        public string E_LOGIN_DATE { get; set; }
        public string E_UPDATE_DATE { get; set; }
        public string E_KEY { get; set; }
    }
}
