//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_main_profile
    {
        public int S_ID { get; set; }
        public int B_ID { get; set; }
        public string B_REPORT { get; set; }
        public string S_TYPE { get; set; }
        public string B_ROLE { get; set; }
        public Nullable<double> B_MONTH_NUM { get; set; }
        public string B_PRIVILEGES { get; set; }
        public int B_MEMBER { get; set; }
    }
}
