//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_moderator
    {
        public int U_ID { get; set; }
        public string U_NAME { get; set; }
        public string U_USERNAME { get; set; }
        public string U_PASSWORD { get; set; }
        public string U_EMAIL { get; set; }
        public string U_RIGHT { get; set; }
        public string U_GROUP { get; set; }
        public string U_LAST_LOGIN { get; set; }
        public string MOBILE { get; set; }
        public int ISUSER { get; set; }
    }
}
