//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_review
    {
        public int b_id { get; set; }
        public int userid { get; set; }
        public string type { get; set; }
        public int point { get; set; }
        public string note { get; set; }
        public int addtime { get; set; }
        public string review { get; set; }
        public int point1 { get; set; }
        public string note1 { get; set; }
        public int point2 { get; set; }
        public string note2 { get; set; }
        public int point3 { get; set; }
        public string note3 { get; set; }
        public int point4 { get; set; }
        public string note4 { get; set; }
        public int point5 { get; set; }
        public string note5 { get; set; }
        public int point6 { get; set; }
        public string note6 { get; set; }
        public int point7 { get; set; }
        public string note7 { get; set; }
        public int point8 { get; set; }
        public string note8 { get; set; }
        public string note_con { get; set; }
        public string note_mon { get; set; }
        public int status { get; set; }
        public int sendtime { get; set; }
        public string file { get; set; }
    }
}
