//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_journal
    {
        public int J_ID { get; set; }
        public string ISSN { get; set; }
        public string J_ABBR { get; set; }
        public string J_FULL { get; set; }
        public string J_DESCRIPTION { get; set; }
        public Nullable<int> J_FROM { get; set; }
        public string J_LANGUAGE { get; set; }
    }
}
