//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_finare_use
    {
        public int id { get; set; }
        public int idl { get; set; }
        public int idc { get; set; }
        public string content { get; set; }
        public double accept { get; set; }
        public double impleme { get; set; }
        public string note { get; set; }
    }
}
