//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_finare_list
    {
        public int id { get; set; }
        public int B_ID { get; set; }
        public string project_name { get; set; }
        public string project_code { get; set; }
        public string organization { get; set; }
        public int addtime { get; set; }
        public int sendtime { get; set; }
        public int contract_month { get; set; }
        public int cdate_begin { get; set; }
        public int cdate_end { get; set; }
        public int exten_month { get; set; }
        public int actual_month { get; set; }
        public int adate_begin { get; set; }
        public int adate_end { get; set; }
        public double total_cost { get; set; }
        public string target { get; set; }
        public string content_range { get; set; }
        public string method { get; set; }
        public string result { get; set; }
        public string changes { get; set; }
        public int num_regisi { get; set; }
        public int num_pubisi { get; set; }
        public string recom { get; set; }
        public int userid { get; set; }
        public string area { get; set; }
        public int status { get; set; }
    }
}
