//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_action
    {
        public int A_ID { get; set; }
        public string A_SUBJECT { get; set; }
        public string A_SUBJECT_TYPE { get; set; }
        public string A_OBJECT { get; set; }
        public string A_OBJECT_TYPE { get; set; }
        public string A_NAME { get; set; }
        public string A_DESCRIPTION { get; set; }
        public string A_TIME { get; set; }
        public string A_DATE { get; set; }
    }
}
