//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_publication
    {
        public int P_ID { get; set; }
        public int S_ID { get; set; }
        public sbyte P_LANGUAGE { get; set; }
        public string P_DETAIL { get; set; }
        public string P_TITLE { get; set; }
        public string P_ABSTRACT { get; set; }
        public string P_MAIN_AUTHOR { get; set; }
        public string P_TYPE { get; set; }
        public string P_PUBLISHER { get; set; }
        public string P_ISSN { get; set; }
        public string P_TIME { get; set; }
        public string P_YEAR { get; set; }
        public string P_ISI { get; set; }
        public string P_NUMBER { get; set; }
        public string P_NOTE { get; set; }
        public string P_UPDATE_DATE { get; set; }
        public string P_KEY { get; set; }
        public Nullable<int> P_CATE { get; set; }
        public string P_UPLOAD { get; set; }
    }
}
